---
title: "Practical 1"
format: html
---

## Question 1

```{r}
# Load the airquality dataset 
data("airquality")

# Find rows with missing values
missing_rows <- airquality[!complete.cases(airquality), ]

# Display the rows with missing values
print(missing_rows)
```

## Question 2

```{r}
# Function to find sd, mean, min, max

sumstats <- function(x) {
  stats <- data.frame(
    StdDev = sd(x, na.rm = TRUE), # ignoring missing values
    Mean = mean(x, na.rm = TRUE),
    Min = min(x, na.rm = TRUE),
    Max = max(x, na.rm = TRUE)
  )
  return(stats)
}

print(sumstats(airquality$Ozone))
print(sumstats(airquality$Temp))
```

## Question 3

```{r}
# Load the built-in cars dataset
data("cars")

# Define response (Y) and predictor (X) variables
y <- cars$dist
x <- cbind(1, cars$speed)  # Design matrix (adding intercept column of 1s)

# Function to compute beta estimates, standard errors using the normal equation
beta_hat <- solve(t(x) %*% x) %*% t(x) %*% y

# Display the estimated coefficients
colnames(beta_hat) <- c("Estimate")
rownames(beta_hat) <- c("Intercept", "Speed")
print(beta_hat)
```

## Question 4

```{r}
# Check computed estimates against lm function output
model1 <- lm(dist~speed, data=cars)
summary(model1)

# Display results
cat("Matrix Calculation Estimates:\n")
print(beta_hat)

cat("\nLM Function Estimates:\n")
print(coef(model1))
```
